<?php

namespace Tests;

use Entity\Person;

include_once __DIR__."/../Entity/Person.php";

class PersonTest extends \PHPUnit_Framework_TestCase
{

    private $person;

    protected function setUp()
    {
        $this->person = new Person();
    }

    public function testFirstname()
    {
        $this->person->setFirstname("Manuel");

        $this->assertInternalType("string", $this->person->getFirstname());
    }

    public function testLastname()
    {
        $this->person->setLastname("Stieger");

        $this->assertInternalType("string", $this->person->getLastname());
    }

    public function testAge()
    {
        $this->person->setAge(26);

        $this->assertInternalType("int", $this->person->getAge());
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
