<?php

namespace Tests;

use Entity\Queue;

include_once __DIR__."/../Entity/Queue.php";

class QueueTest extends \PHPUnit_Framework_TestCase
{

    private $queue;

    protected function setUp()
    {
        $this->queue = new Queue();
    }

    public function testAdd()
    {
        $person = array(
            "firstname" => "Manuel",
            "lastname" => "Stieger",
            "age" => 26
        );

        $this->queue->add($person);

        $this->assertInternalType("array", $this->queue->getQueue());

        $this->assertEquals(1, $this->queue->getLength());
    }

    public function testRemove()
    {
        $person = array(
            "firstname" => "Manuel",
            "lastname" => "Stieger",
            "age" => 26
        );

        $this->queue->add($person);

        $this->assertEquals(1, $this->queue->getLength());

        $this->queue->remove($person);

        $this->assertEquals(0, $this->queue->getLength());
    }

    public function testWriteFile()
    {
        $this->queue = new Queue();

        $person = array(
            "firstname" => "Manuel",
            "lastname" => "Stieger",
            "age" => 26
        );

        $this->queue->add($person);

        $this->queue->writeFile();
    }

    public function testReadFile()
    {
        $this->queue = new Queue();

        $this->queue->readFile();

        $this->assertInternalType("array", $this->queue->getQueue());
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
